# Generated by Django 2.0.3 on 2018-03-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='choice_text',
            new_name='Pdf_articulo',
        ),
    ]
