# Generated by Django 2.0.3 on 2018-03-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.FileField(max_length=200, upload_to='')),
                ('Titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario_Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto_Respuesta', models.CharField(max_length=200)),
                ('Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foros.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto_Pregunta', models.CharField(max_length=200)),
                ('Fecha_Publicacion', models.DateTimeField(verbose_name='date published')),
                ('Estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto_Respuesta', models.CharField(max_length=200)),
                ('Pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foros.Pregunta')),
            ],
        ),
    ]
